cmake_minimum_required(VERSION 3.20)
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/VERSION.txt" VERSION)
project(
	stlc
	VERSION ${VERSION}
	LANGUAGES C)
message(STATUS "Configurando '${PROJECT_NAME}' versión: ${VERSION}")
if(PROJECT_IS_TOP_LEVEL)
	set(CMAKE_COLOR_DIAGNOSTICS ON)
	set(CMAKE_COLOR_MAKEFILE ON)
	set(CMAKE_POSITION_INDEPENDENT_CODE ON)
	if(NOT (CMAKE_BUILD_TYPE STREQUAL "Debug"))
		set(BUILD_SHARED_LIBS OFF)
	else()
		set(BUILD_SHARED_LIBS ON)
	endif()
	include(CTest)
	message(CHECK_START "Buscando ccache...")
	find_program(CCACHE_PROGRAM ccache)
	if(CCACHE_PROGRAM)
		message(CHECK_PASS "ccache disponible")
		set(CMAKE_C_COMPILER_LAUNCHER ${CCACHE_PROGRAM})
		set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE_PROGRAM})
	else()
		message(CHECK_FAIL "ccache no encontrado")
	endif()
	include(CheckIPOSupported)
	message(CHECK_START "check_ipo_supported...")
	check_ipo_supported(RESULT ipo_supported)
	if(ipo_supported)
		message(CHECK_PASS "IPO soportado")
	else()
		message(CHECK_FAIL "IPO no soportado")
	endif()
	# Directorio de dependencias 'header-only'
	set(EXTERNAL "${CMAKE_CURRENT_BINARY_DIR}/external")
	file(MAKE_DIRECTORY "${EXTERNAL}")
endif()
add_subdirectory("src")
add_subdirectory("tests")