#define basic_string(C) \
	struct {              \
		size_t _size;       \
		size_t _capacity;   \
		C* _data;           \
	}
#define basic_string_at(this, index) (basic_string_data(this)[index])
#define basic_string_front(this)		 (basic_string_data(this)[0u])
#define basic_string_back(this)			 (basic_string_data(this)[basic_string_size(this) - 1u])
#define basic_string_data(this)			 ((this)->_data)
#define basic_string_c_str(this)		 ((const typeof_unqual(basic_string_data(this))*)basic_string_data(this))
#define basic_string_empty(this)		 (basic_string_size(this) == 0u)
#define basic_string_size(this)			 ((this)->_size)
#define basic_string_length(this)		 (basic_string_size(this))
#define basic_string_max_size(this)	 SIZE_MAX
// #define basic_string_reserve(this)
#define basic_string_capacity(this) ((this)->_capacity)
// #define basic_string_shrink_to_fit(this)
#define basic_string_clear(this) (basic_string_size(this) = 0u)
// #define basic_string_insert(this)
// #define basic_string_insert_range(this)
// #define basic_string_erase(this)
// #define basic_string_push_back(this)
// #define basic_string_pop_back(this)
// #define basic_string_append(this)
// #define basic_string_append_range(this)
// #define basic_string_replace(this)
// #define basic_string_replace_with_range(this)
// #define basic_string_copy(this)
// #define basic_string_resize(this)
// #define basic_string_resize_and_overwrite(this)
// #define basic_string_swap(this)
// #define basic_string_find(this)
// #define basic_string_rfind(this)
// #define basic_string_find_first_of(this)
// #define basic_string_find_first_not_of(this)
// #define basic_string_find_last_of(this)
// #define basic_string_find_last_not_of(this)
// #define basic_string_compare(this)
// #define basic_string_starts_with(this)
// #define basic_string_ends_with(this)
// #define basic_string_contains(this)
// #define basic_string_substr(this)
// #define basic_string_subview(this)